const mongoose = require('mongoose');

const resellerApiProjectSchema = new mongoose.Schema({
  name: { type: String, trim: true, required: true },
  website: { type: String, trim: true, default: '' },
  product: { type: String, enum: ['domain','bank'], required: true },
  domainSandboxPublicKey: { type: String, default: '' },
  domainSandboxSecretHash: { type: String, default: '' },
  domainSandboxSecretEncrypted: { type: String, default: '' },
  domainLivePublicKey: { type: String, default: '' },
  domainLiveSecretHash: { type: String, default: '' },
  domainLiveSecretEncrypted: { type: String, default: '' },
  bankSandboxPublicKey: { type: String, default: '' },
  bankSandboxSecretHash: { type: String, default: '' },
  bankSandboxSecretEncrypted: { type: String, default: '' },
  bankLivePublicKey: { type: String, default: '' },
  bankLiveSecretHash: { type: String, default: '' },
  bankLiveSecretEncrypted: { type: String, default: '' },
  scopes: { type:[String], default:[] },
  revokedAt: { type:Date, default:null },
  webhookUrl: { type:String, default:'' },
  webhookSigningSecretHash: { type:String, default:'' },
  webhookSigningSecretEncrypted: { type:String, default:'' },
  allowedIps: { type:[String], default:[] },
  lastKeyCreatedAt: Date
}, { timestamps: true });
const resellerProfileSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true, index: true },
  businessName: { type: String, trim: true, required: true },
  country: { type: String, trim: true, default: '' },
  registrationNumber: { type: String, trim: true, default: '' },
  website: { type: String, trim: true, default: '' },
  useCase: { type: String, trim: true, default: '' },
  products: [{ type: String, enum: ['domain_api','bank_api'] }],
  status: { type: String, enum: ['pending','sandbox_approved','approved','rejected','suspended'], default: 'sandbox_approved' },
  domainApiStatus: { type: String, enum: ['pending','sandbox','live','rejected','suspended'], default: 'sandbox' },
  bankApiStatus: { type: String, enum: ['pending','sandbox','live','rejected','suspended'], default: 'sandbox' },
  sandboxPublicKey: { type: String, default: '' },
  sandboxSecretHash: { type: String, default: '' },
  livePublicKey: { type: String, default: '' },
  liveSecretHash: { type: String, default: '' },
  domainSandboxPublicKey: { type: String, default: '', index: true },
  domainSandboxSecretHash: { type: String, default: '' },
  domainLivePublicKey: { type: String, default: '', index: true },
  domainLiveSecretHash: { type: String, default: '' },
  bankSandboxPublicKey: { type: String, default: '', index: true },
  bankSandboxSecretHash: { type: String, default: '' },
  bankLivePublicKey: { type: String, default: '', index: true },
  bankLiveSecretHash: { type: String, default: '' },
  lastKeyCreatedAt: Date,
  apiProjects: { type: [resellerApiProjectSchema], default: [] },
  lifetimeFreeApiAccess: { type: Boolean, default: false },
  lastActiveBankingTransactionAt: { type: Date, default: null }
}, { timestamps: true });
module.exports = mongoose.model('ResellerProfile', resellerProfileSchema);
